name: Mac CI

on:
  push:
  pull_request:

jobs:
  ubsan:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          brew install cmake ninja; brew install openssl protobuf libsodium
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git submodule update --init --force --recursive

      - name: Test with ubsan
        run: |
          mkdir build
          pushd build
          cmake -DSANITIZE_UNDEFINED=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib ../
          make -j`nproc`
          TSAN_OPTIONS="suppressions=../test/test_tsan.suppression" ./et-test
          popd
          rm -Rf build

  asan:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git submodule update --init --force --recursive
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          brew install cmake ninja; brew install openssl protobuf libsodium

      - name: Test with asan
        run: |
          mkdir build
          pushd build
          cmake -DSANITIZE_ADDRESS=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib ../
          make -j`nproc`
          TSAN_OPTIONS="suppressions=../test/test_tsan.suppression" ./et-test
          popd
          rm -Rf build

  msan:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git submodule update --init --force --recursive
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          brew install cmake ninja; brew install openssl protobuf libsodium

      - name: Test with msan
        run: |
          mkdir build
          pushd build
          cmake -DSANITIZE_MEMORY=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib ../
          make -j`nproc`
          TSAN_OPTIONS="suppressions=../test/test_tsan.suppression" ./et-test
          popd
          rm -Rf build

  tsan:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git submodule update --init --force --recursive
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          brew install cmake ninja; brew install openssl protobuf libsodium

      - name: Test with tsan
        run: |
          mkdir build
          pushd build
          cmake -DSANITIZE_THREAD=ON -DSANITIZE_LINK_STATIC=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib ../
          make -j`nproc`
          TSAN_OPTIONS="suppressions=../test/test_tsan.suppression" ./et-test
          popd
          rm -Rf build
